export const mockProducts = [
  {
    "id": "prod-1",
    "name_bn": "Premium Makeup Set 1",
    "name_en": "Premium Makeup Set 1",
    "price": 1050,
    "image_url": "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&q=80&w=400",
    "unit": "1 Pc",
    "category": "makeup",
    "discount_price": null,
    "discount_percent": null,
    "description_bn": "এটি একটি প্রিমিয়াম কোয়ালিটির Premium Makeup Set",
    "description_en": "This is a premium quality Premium Makeup Set",
    "is_active": true,
    "is_popular": true,
    "created_at": "2026-10-08T14:33:27.300Z"
  },
  {
    "id": "prod-2",
    "name_bn": "Premium Makeup Set 2",
    "name_en": "Premium Makeup Set 2",
    "price": 1100,
    "image_url": "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&q=80&w=400",
    "unit": "1 Pc",
    "category": "makeup",
    "discount_price": null,
    "discount_percent": null,
    "description_bn": "এটি একটি প্রিমিয়াম কোয়ালিটির Premium Makeup Set",
    "description_en": "This is a premium quality Premium Makeup Set",
    "is_active": true,
    "is_popular": true,
    "created_at": "2026-10-08T14:33:27.301Z"
  },
  {
    "id": "prod-3",
    "name_bn": "Premium Makeup Set 3",
    "name_en": "Premium Makeup Set 3",
    "price": 1150,
    "image_url": "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&q=80&w=400",
    "unit": "1 Pc",
    "category": "makeup",
    "discount_price": 1120,
    "discount_percent": 10,
    "description_bn": "এটি একটি প্রিমিয়াম কোয়ালিটির Premium Makeup Set",
    "description_en": "This is a premium quality Premium Makeup Set",
    "is_active": true,
    "is_popular": false,
    "created_at": "2026-10-08T14:33:27.301Z"
  },
  {
    "id": "prod-4",
    "name_bn": "Premium Makeup Set 4",
    "name_en": "Premium Makeup Set 4",
    "price": 1200,
    "image_url": "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&q=80&w=400",
    "unit": "1 Pc",
    "category": "makeup",
    "discount_price": null,
    "discount_percent": null,
    "description_bn": "এটি একটি প্রিমিয়াম কোয়ালিটির Premium Makeup Set",
    "description_en": "This is a premium quality Premium Makeup Set",
    "is_active": true,
    "is_popular": false,
    "created_at": "2026-10-08T14:33:27.302Z"
  },
  {
    "id": "prod-5",
    "name_bn": "Premium Makeup Set 5",
    "name_en": "Premium Makeup Set 5",
    "price": 1250,
    "image_url": "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&q=80&w=400",
    "unit": "1 Pc",
    "category": "makeup",
    "discount_price": null,
    "discount_percent": null,
    "description_bn": "এটি একটি প্রিমিয়াম কোয়ালিটির Premium Makeup Set",
    "description_en": "This is a premium quality Premium Makeup Set",
    "is_active": true,
    "is_popular": false,
    "created_at": "2026-10-08T14:33:27.302Z"
  },
  {
    "id": "prod-11",
    "name_bn": "Elegant Necklace 1",
    "name_en": "Elegant Necklace 1",
    "price": 2550,
    "image_url": "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=400",
    "unit": "1 Pc",
    "category": "juwelary",
    "discount_price": null,
    "discount_percent": null,
    "description_bn": "এটি একটি প্রিমিয়াম কোয়ালিটির Elegant Necklace",
    "description_en": "This is a premium quality Elegant Necklace",
    "is_active": true,
    "is_popular": true,
    "created_at": "2026-10-08T14:33:27.302Z"
  },
  {
    "id": "prod-12",
    "name_bn": "Elegant Necklace 2",
    "name_en": "Elegant Necklace 2",
    "price": 2600,
    "image_url": "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=400",
    "unit": "1 Pc",
    "category": "juwelary",
    "discount_price": null,
    "discount_percent": null,
    "description_bn": "এটি একটি প্রিমিয়াম কোয়ালিটির Elegant Necklace",
    "description_en": "This is a premium quality Elegant Necklace",
    "is_active": true,
    "is_popular": true,
    "created_at": "2026-10-08T14:33:27.302Z"
  },
  {
    "id": "prod-13",
    "name_bn": "Elegant Necklace 3",
    "name_en": "Elegant Necklace 3",
    "price": 2650,
    "image_url": "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=400",
    "unit": "1 Pc",
    "category": "juwelary",
    "discount_price": 2620,
    "discount_percent": 10,
    "description_bn": "এটি একটি প্রিমিয়াম কোয়ালিটির Elegant Necklace",
    "description_en": "This is a premium quality Elegant Necklace",
    "is_active": true,
    "is_popular": false,
    "created_at": "2026-10-08T14:33:27.302Z"
  },
  {
    "id": "prod-14",
    "name_bn": "Elegant Necklace 4",
    "name_en": "Elegant Necklace 4",
    "price": 2700,
    "image_url": "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=400",
    "unit": "1 Pc",
    "category": "juwelary",
    "discount_price": null,
    "discount_percent": null,
    "description_bn": "এটি একটি প্রিমিয়াম কোয়ালিটির Elegant Necklace",
    "description_en": "This is a premium quality Elegant Necklace",
    "is_active": true,
    "is_popular": false,
    "created_at": "2026-10-08T14:33:27.302Z"
  },
  {
    "id": "prod-15",
    "name_bn": "Elegant Necklace 5",
    "name_en": "Elegant Necklace 5",
    "price": 2750,
    "image_url": "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=400",
    "unit": "1 Pc",
    "category": "juwelary",
    "discount_price": null,
    "discount_percent": null,
    "description_bn": "এটি একটি প্রিমিয়াম কোয়ালিটির Elegant Necklace",
    "description_en": "This is a premium quality Elegant Necklace",
    "is_active": true,
    "is_popular": false,
    "created_at": "2026-10-08T14:33:27.302Z"
  },
  {
    "id": "prod-21",
    "name_bn": "Luxury Skincare 1",
    "name_en": "Luxury Skincare 1",
    "price": 850,
    "image_url": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=400",
    "unit": "1 Pc",
    "category": "cosmetics",
    "discount_price": null,
    "discount_percent": null,
    "description_bn": "এটি একটি প্রিমিয়াম কোয়ালিটির Luxury Skincare",
    "description_en": "This is a premium quality Luxury Skincare",
    "is_active": true,
    "is_popular": true,
    "created_at": "2026-10-08T14:33:27.302Z"
  },
  {
    "id": "prod-22",
    "name_bn": "Luxury Skincare 2",
    "name_en": "Luxury Skincare 2",
    "price": 900,
    "image_url": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=400",
    "unit": "1 Pc",
    "category": "cosmetics",
    "discount_price": null,
    "discount_percent": null,
    "description_bn": "এটি একটি প্রিমিয়াম কোয়ালিটির Luxury Skincare",
    "description_en": "This is a premium quality Luxury Skincare",
    "is_active": true,
    "is_popular": true,
    "created_at": "2026-10-08T14:33:27.302Z"
  },
  {
    "id": "prod-23",
    "name_bn": "Luxury Skincare 3",
    "name_en": "Luxury Skincare 3",
    "price": 950,
    "image_url": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=400",
    "unit": "1 Pc",
    "category": "cosmetics",
    "discount_price": 920,
    "discount_percent": 10,
    "description_bn": "এটি একটি প্রিমিয়াম কোয়ালিটির Luxury Skincare",
    "description_en": "This is a premium quality Luxury Skincare",
    "is_active": true,
    "is_popular": false,
    "created_at": "2026-10-08T14:33:27.302Z"
  },
  {
    "id": "prod-24",
    "name_bn": "Luxury Skincare 4",
    "name_en": "Luxury Skincare 4",
    "price": 1000,
    "image_url": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=400",
    "unit": "1 Pc",
    "category": "cosmetics",
    "discount_price": null,
    "discount_percent": null,
    "description_bn": "এটি একটি প্রিমিয়াম কোয়ালিটির Luxury Skincare",
    "description_en": "This is a premium quality Luxury Skincare",
    "is_active": true,
    "is_popular": false,
    "created_at": "2026-10-08T14:33:27.302Z"
  },
  {
    "id": "prod-25",
    "name_bn": "Luxury Skincare 5",
    "name_en": "Luxury Skincare 5",
    "price": 1050,
    "image_url": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=400",
    "unit": "1 Pc",
    "category": "cosmetics",
    "discount_price": null,
    "discount_percent": null,
    "description_bn": "এটি একটি প্রিমিয়াম কোয়ালিটির Luxury Skincare",
    "description_en": "This is a premium quality Luxury Skincare",
    "is_active": true,
    "is_popular": false,
    "created_at": "2026-10-08T14:33:27.302Z"
  },
  {
    "id": "prod-31",
    "name_bn": "Designer Bag 1",
    "name_en": "Designer Bag 1",
    "price": 3050,
    "image_url": "https://images.unsplash.com/photo-1584916201218-f4242ceb4809?auto=format&fit=crop&q=80&w=400",
    "unit": "1 Pc",
    "category": "bag",
    "discount_price": null,
    "discount_percent": null,
    "description_bn": "এটি একটি প্রিমিয়াম কোয়ালিটির Designer Bag",
    "description_en": "This is a premium quality Designer Bag",
    "is_active": true,
    "is_popular": true,
    "created_at": "2026-10-08T14:33:27.302Z"
  },
  {
    "id": "prod-32",
    "name_bn": "Designer Bag 2",
    "name_en": "Designer Bag 2",
    "price": 3100,
    "image_url": "https://images.unsplash.com/photo-1584916201218-f4242ceb4809?auto=format&fit=crop&q=80&w=400",
    "unit": "1 Pc",
    "category": "bag",
    "discount_price": null,
    "discount_percent": null,
    "description_bn": "এটি একটি প্রিমিয়াম কোয়ালিটির Designer Bag",
    "description_en": "This is a premium quality Designer Bag",
    "is_active": true,
    "is_popular": true,
    "created_at": "2026-10-08T14:33:27.302Z"
  },
  {
    "id": "prod-33",
    "name_bn": "Designer Bag 3",
    "name_en": "Designer Bag 3",
    "price": 3150,
    "image_url": "https://images.unsplash.com/photo-1584916201218-f4242ceb4809?auto=format&fit=crop&q=80&w=400",
    "unit": "1 Pc",
    "category": "bag",
    "discount_price": 3120,
    "discount_percent": 10,
    "description_bn": "এটি একটি প্রিমিয়াম কোয়ালিটির Designer Bag",
    "description_en": "This is a premium quality Designer Bag",
    "is_active": true,
    "is_popular": false,
    "created_at": "2026-10-08T14:33:27.302Z"
  },
  {
    "id": "prod-34",
    "name_bn": "Designer Bag 4",
    "name_en": "Designer Bag 4",
    "price": 3200,
    "image_url": "https://images.unsplash.com/photo-1584916201218-f4242ceb4809?auto=format&fit=crop&q=80&w=400",
    "unit": "1 Pc",
    "category": "bag",
    "discount_price": null,
    "discount_percent": null,
    "description_bn": "এটি একটি প্রিমিয়াম কোয়ালিটির Designer Bag",
    "description_en": "This is a premium quality Designer Bag",
    "is_active": true,
    "is_popular": false,
    "created_at": "2026-10-08T14:33:27.302Z"
  },
  {
    "id": "prod-35",
    "name_bn": "Designer Bag 5",
    "name_en": "Designer Bag 5",
    "price": 3250,
    "image_url": "https://images.unsplash.com/photo-1584916201218-f4242ceb4809?auto=format&fit=crop&q=80&w=400",
    "unit": "1 Pc",
    "category": "bag",
    "discount_price": null,
    "discount_percent": null,
    "description_bn": "এটি একটি প্রিমিয়াম কোয়ালিটির Designer Bag",
    "description_en": "This is a premium quality Designer Bag",
    "is_active": true,
    "is_popular": false,
    "created_at": "2026-10-08T14:33:27.302Z"
  }
];

export const mockSettings = [
  {
    id: 1,
    hero_slides: [
      {
        image_url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=1600',
        titleBn: 'ফ্যাশন এখন ঘরে',
        titleEn: 'Fashion now at home',
        subtitleBn: 'সেরা কোয়ালিটির প্রোডাক্টস।',
        subtitleEn: 'Best quality products for your lifestyle.'
      }
    ]
  }
];

export const mockOrders = [
  {
    id: 'ord-1',
    short_id: 'ORD-123456',
    customer_name: 'John Doe',
    customer_phone: '01711223344',
    customer_address: 'Dhaka, Bangladesh',
    total_amount: 1400,
    status: 'pending',
    created_at: new Date().toISOString(),
    items: [
      {
        product_id: 'prod-1',
        quantity: 2,
        price: 350
      }
    ]
  }
];
